import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "lenis/react";
import { cn } from "@/lib/utils";
import Script from "next/script";

const roboto = Roboto({
  variable: "--font-robot",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crt Lukas Bozic - Fullstack developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script src="./fluid.js" />
      </head>
      <body className={cn("bg-background antialiased", roboto.variable)}>
        {children}

        <ReactLenis root />
        <canvas
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100%",
            height: "100%",
            zIndex: -3,
            pointerEvents: "all",
          }}
        />
      </body>
    </html>
  );
}
